### ISSUE TITLE
Click and drag automatically fills cells

### ISSUE THREAD

**Issue by ghost** [LukeStorry/bool-array-filler#2]
Is it possible for the cells to be filled if you click and drag over them? This means you don't have to individually click each one.

**Comment by LukeStorry** [comment]
Probably!
Have a go at it, you'd want to change the button component to call the
callback on mouse over as well as on click.

**Comment by ghost** [comment]
I'm very confused,
when I change [this](https://github.com/LukeStorry/bool-array-filler/blob/a4f601135329e3ebbcbbd78a1b9336edcb493aca/index.js#L73) line to
```js
onClick=${console.log("click")}
```
there is 144 logs when the page loads, but no logs when I'm clicking the cells?

**Comment by ghost** [comment]
Also, if I change it to
```js
onClick=${function() { updateCell(rowIndex, colIndex) }}
```
then the `updateCell` function isn't being called anymore, even though it should be?

**Comment by LukeStorry** [comment]
This: `onClick=${console.log("click")}` will call that console.log every render, but then because it doesn't return anything, the onClick won't do anything.
It needs to be wrapped in a function to work, so either
`onClick=${() => console.log("click")}` or `onClick=${function() {console.log("click")}}`


Your confusion is because I have set up `updateCell` to be a function that returns a function:
```updateCell = (rowIndex, colIndex) => () => {```
This means that the usual ``() =>`` is not needed, `updateCell` already returns the wrapped function to use.

**Comment by LukeStorry** [comment]
Changed it so it will keep track and not flip all cells, but continue filling with the colour first clicked on.

**Comment by LukeStorry** [comment]
@aimorris Try refreshing your browser cache, it works for me.
What browser are you using?

**Comment by ghost** [comment]
Firefox on Manjaro,
I refreshed browser cache and it's still not working,

**Comment by ghost** [comment]
![2020-04-16-080020_780x40_scrot](https://user-images.githubusercontent.com/1687121/79393264-57162300-7fb8-11ea-9574-683e63ff7114.png)

**Comment by LukeStorry** [comment]
Ah yeah, Firefox calls it `e.relatedTarget` and Chrome is `e.fromElement`.

Possible alternative would be a refactor to change the Input Functional-Component to a stateful ClassComponent, and store the dragType in the state, but this way of just checking the previous cell's status and setting it is cleaner, and I avoid state wherever possible.

Fixed in the [latest commit](https://github.com/LukeStorry/bool-array-filler/commit/93cf506a4072ab21e02e89c45b323582712b6b26).

**Comment by ghost** [comment]
Works now!
:)

**Comment by LukeStorry** [comment]
🥳
